### ISSUE TITLE
CRUD user-management backend

### ISSUE THREAD

**Issue by Wallensteiner0** [ZuzkaGlaess/driving-school-booking-app-backend-V2#34]
adopt the Database to be able to edit users
- delete 
- update
- create a user

**Comment by ZuzkaGlaess** [comment]
Andi, if you already contributed to this branch pls update it (if not you can delete it and create new one, so all changes from master are up-to-date).
Then you can create 2 methods (get - to get all users and delete - single user) in ProfilesController.
Afterwards pls. write test for each of these 2 methods.
Thanks

**Comment by ZuzkaGlaess** [comment]
Already implemented
