### ISSUE TITLE
User Management for Admin (CRUD)

### ISSUE THREAD

**Issue by Wallensteiner0** [ZuzkaGlaess/driving-school-booking-app-backend-V2#42]
This Task is backend and frontend related.
Before starting this task the user data should be persistent in the database.

As an admin 
- I want to see a list of all Users, their role (user, teacher, admin) and status (active, deactivated).
- I want to change the role of an user (to techacher, admin or vis versa)
- I want to deactivate or re-activate a user

**Comment by ZuzkaGlaess** [comment]
already implemented
